### ISSUE TITLE
4. Median of 2 sorted array

### ISSUE THREAD

**Issue by Lorem-24K** [Lorem-24K/Leetcode-Solution#4]

**Comment by Xtha-Sunil** [comment]
Hello I am doing leetcoding, could you assign me all issue. I will post my solutions All are efficient and optimized one.

**Comment by Xtha-Sunil** [comment]
Hello I am doing leetcoding, could you assign me all issue. I will post my solutions All are efficient and optimized one.

**Comment by Lorem-24K** [comment]
Ok
